Importing Numpy Library to the module to perform operations

In [ ]:
import numpy as np

In [ ]:


arr = np.array([10,20,30])
arr

array([10, 20, 30])

In [ ]:

arr =np.array([10,20.,30])
arr

array([10., 20., 30.])

Here we used heterogeneous value instead of homogeneous value. i,e We used combination of int and float as values. As the operation is done the array will be converted to float because the float holds the higher priority in array.

array priority : bool < int < float < complex < str < object -> set{} & dict{}

In [ ]:

arr = np.array([10+2j,20,30])
arr

array([10.+2.j, 20.+0.j, 30.+0.j])

creating 2D array

In [ ]:
arr_2d = np.array([[10,20,30],[30,40,50]])
arr_2d

array([[10, 20, 30],
       [30, 40, 50]])

Creating 3D array

In [ ]:
arr_3d = np.array([[[10,20,30],[30,40,50],[23,34,45]],
                  [[100,200,300],[400,500,600],[23,45,67]]])
arr_3d

array([[[ 10,  20,  30],
        [ 30,  40,  50],
        [ 23,  34,  45]],

       [[100, 200, 300],
        [400, 500, 600],
        [ 23,  45,  67]]])

variables for array

ndim - used to check dimensions of an array

In [ ]:
arr.ndim
arr_2d.ndim
arr_3d.ndim

3

Reshaping 1D array into nD array

In [ ]:
arr = np.array([10,20,30,40,50,60])
arr


array([10, 20, 30, 40, 50, 60])

converting 1D to 2D

In [ ]:
arr.reshape(2,3)

array([[10, 20, 30],
       [40, 50, 60]])

In [ ]:
arr.reshape(3,2)

array([[10, 20],
       [30, 40],
       [50, 60]])

In [ ]:
arr.reshape(1,6)

array([[10, 20, 30, 40, 50, 60]])

In [ ]:
arr.reshape(6,1)

array([[10],
       [20],
       [30],
       [40],
       [50],
       [60]])

converting 1D to 3D

In [ ]:
arr.reshape(1,3,2)

array([[[10, 20],
        [30, 40],
        [50, 60]]])

In [ ]:
arr.reshape(1,2,3)

array([[[10, 20, 30],
        [40, 50, 60]]])

In [ ]:
arr.reshape(2,3,1)

array([[[10],
        [20],
        [30]],

       [[40],
        [50],
        [60]]])

converting nD to 1D using reshape()

In [ ]:
arr_3d.reshape(-1)

array([ 10,  20,  30,  30,  40,  50,  23,  34,  45, 100, 200, 300, 400,
       500, 600,  23,  45,  67])

converting nD to 1D using flatten()

In [ ]:
arr_3d.flatten()

array([ 10,  20,  30,  30,  40,  50,  23,  34,  45, 100, 200, 300, 400,
       500, 600,  23,  45,  67])

converting nD to 1D using ravel()

In [ ]:
arr_3d.ravel()

array([ 10,  20,  30,  30,  40,  50,  23,  34,  45, 100, 200, 300, 400,
       500, 600,  23,  45,  67])

In [ ]:
arr_2d.reshape(-1)

array([10, 20, 30, 30, 40, 50])

In [ ]:
arr_2d.flatten()

array([10, 20, 30, 30, 40, 50])

In [ ]:
arr_2d.ravel()

array([10, 20, 30, 30, 40, 50])

generating series of number using arange

In [ ]:
np.arange(2,10,0.5)

array([2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. , 7.5, 8. ,
       8.5, 9. , 9.5])

In [ ]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(1,101).reshape(10,10)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [ ]:
np.arange(1,101).reshape(10,10).size

100

In [ ]:
np.linspace(1,10)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [ ]:
np.zeros((2,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
np.ones((3,3),dtype=float)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

Array Creation Methods

create a array using arange

In [ ]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

creating a array using linspace

In [ ]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

creating array using zeros 1D

In [ ]:
np.zeros(3)

array([0., 0., 0.])

creating array using zeros - 2D

In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

creating array using zeros - 3D

In [ ]:
np.zeros((1,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
a = np.array([10,20,30,40,50])
a

array([10, 20, 30, 40, 50])

In [ ]:
b = a.copy()
b[4]=5000
print(a)
print(b)

[10 20 30 40 50]
[  10   20   30   40 5000]


In [ ]:
c = a.view()
c[3] = 100
print(a)
print(c)

[ 10  20  30 100  50]
[ 10  20  30 100  50]


In [ ]:
age = np.array([25,28,32,45,50])
print(age)
print(age.ndim)
print(age.size)

[25 28 32 45 50]
1
5


You are asked to record hourly temperature readings from 6 AM to 6 PM (12 readings), starting from 6 and increasing by 1 hour each time.

In [ ]:
time = np.arange(6,18)
a = np.repeat(time,3)
print(a)
b = np.full
print(b)


[ 6  6  6  7  7  7  8  8  8  9  9  9 10 10 10 11 11 11 12 12 12 13 13 13
 14 14 14 15 15 15 16 16 16 17 17 17]
<function full at 0x7db964f71bc0>


A machine learning engineer is initializing a 5×5 grayscale image matrix where each pixel starts with value 0.Later, she wants to change the center pixel’s value to 255.

In [ ]:
image = np.zeros((5,5),dtype=int)
c_image = image.copy()
c_image[2][2] = 255
print(c_image)

[[  0   0   0   0   0]
 [  0   0   0   0   0]
 [  0   0 255   0   0]
 [  0   0   0   0   0]
 [  0   0   0   0   0]]


In [ ]:
sev_mat = np.full((4,4),7)
sev_mat

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [ ]:
ident_mat = np.identity(4)
ident_mat

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Project 1 : Student details

In [ ]:
st_id = np.arange(5)
st_sub = np.array(['011','012','013','014'])
st_marks = np.array([90,85,80,75,50,34,20,10,98,89,69,96,34,35,35,60,58,55,99,100])


In [ ]:
print(st_id.ndim,st_sub.ndim,st_marks.ndim)
print(st_id.size,st_sub.size,st_marks.size)
print(st_id.shape,st_sub.shape,st_marks.shape)
print(st_marks)


1 1 1
5 4 20
(5,) (4,) (20,)
[ 90  85  80  75  50  34  20  10  98  89  69  96  34  35  35  60  58  55
  99 100]


In [ ]:
st_id_reshape = st_id.reshape(1,-1)

array([[ 90,  85,  80,  75],
       [ 50,  34,  20,  10],
       [ 98,  89,  69,  96],
       [ 34,  35,  35,  60],
       [ 58,  55,  99, 100]])